version: '3.8'
services:

  gateway:
    build: ./gateway
    image: shateit-gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=Europe/Moscow

  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=password
      - TZ=Europe/Moscow

  server:
    build: ./server
    image: shateit-server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=password
      - TZ=Europe/Moscow


