package ru.practicum.shareit.item.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

@Entity
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "items")
public class Item {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    @Column(name = "name")
    private String name;
    @Column(name = "description")
    private String description;
    @Column(name = "available")
    private Boolean available;
    @Column(name = "owner_id")
    private Long owner;
}

//create table if not exists items (
//id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//name varchar (50) not null,
//description varchar (200) not null,
//available  boolean not null,
//owner_id BIGINT not null,
//FOREIGN KEY (owner_id) REFERENCES users (id)
