package ru.practicum.shareit.user.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.Email;

@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "name")
    private String name;

//    @Column(name = "email", unique = true, nullable = false)
    @Column(name = "email")
    @Email
    private String email;
}

//create  TABLE IF NOT EXISTS users (
//  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
//  name VARCHAR(255) NOT NULL,
//  email VARCHAR(512) NOT NULL unique,
//  CONSTRAINT pk_user PRIMARY KEY (id)
//);